---
- hosts: local
  vars:
    userFile: /home/ansible/vars/list
  tasks:
  - name: create file
    file:
      path: "{{ userFile }}"
      state: touch
  - name: generate inventory
    lineinfile:
      path: "{{ userFile }}"
      line: "{{ item }}"
    with_items:
      - "{{ staff }}"
      - "{{ faculty }}"
      - "{{ others }}"

