---
- hosts: all
  user: ansible
  become: yes
  gather_facts: no
  tasks:
    - name: Ensure a job that runs at 5am and 5pm exists. Creates an entry like "0 5,17 * * * df -h >> /tmp/diskspace"
      cron:
        name: "Job 001"
        minute: "0"
        hour: "5,17"
        job: "df -h >> /tmp/diskspace"

    - name: Create an entry like "PATH=/opt/bin" on top on crontab
      cron:
        name: PATH
        env: yes
        job: /opt/bin
        state: absent

    - name: Creates an entry like "APP_HOME=/srv/app" and insert it after path declaration
      cron:
        name: APP_HOME
        env: yes
        job: /srv/app
        insertbefore: PATH
