# Add firewall rule for http service
---
- hosts: all
  user: ansible
  become: yes
  gather_facts: no
  tasks:
    - firewalld:
        service: http
        permanent: yes
        state: enabled
    - name: Restart service firewalld
      service:
        name: firewalld
        state: restarted


