---
- hosts: all
  become: yes
  user: ansible
  tasks:
  - name: install apache
    action: yum name=httpd state=present

  - name: install elinks
    action: yum name=elinks state=present

  - name: Enable Apache on system reboot
    service:
      name: httpd
      enabled: yes

  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started

  - name: install firewalld
    action: yum name=firewalld state=present

  - name: Enable firewalld on system reboot
    service:
      name: firewalld
      enabled: yes

  - name: Start service firewalld, if not started
    service:
      name: firewalld
      state: started

  - name: Add the service http to firewall
    firewalld:
      service: http
      permanent: yes
      state: enabled

  - name: Restart firewalld service
    service:
      name: firewalld
      state: restarted
